var jsondata = {
	'title':'handlebars使用入门', 
	'author': 'gbtags.com', 
	'intro': '基础JS模板引擎handlebars的初学者指南',
  'tutorials':[
      {'title': '第一节：1-handlebar 基础','duration':'5'},
      {'title': '第二节：1-handlebar 表达式','duration':'3'},
      {'title': '第三节：1-handlebar 辅助方法','duration':'1'},
      {'title': '第四节：1-handlebar 内建辅助方法','duration':'6'},
      {'title': '第一节：2-handlebar 基础','duration':'5'},
      {'title': '第二节：2-handlebar 表达式','duration':'3'},
      {'title': '第三节：2-handlebar 辅助方法','duration':'1'},
      {'title': '第四节：2-handlebar 内建辅助方法','duration':'6'},
      {'title': '第一节：3-handlebar 基础','duration':'5'},
      {'title': '第二节：3-handlebar 表达式','duration':'3'},
      {'title': '第三节：3-handlebar 辅助方法','duration':'1'},
      {'title': '第四节：3-handlebar 内建辅助方法','duration':'6'},
      {'title': '第一节：4-handlebar 基础','duration':'5'},
      {'title': '第二节：4-handlebar 表达式','duration':'3'},
      {'title': '第三节：4-handlebar 辅助方法','duration':'1'},
      {'title': '第四节：4-handlebar 内建辅助方法','duration':'6'},
      {'title': '第一节：5-handlebar 基础','duration':'5'},
      {'title': '第二节：5-handlebar 表达式','duration':'3'},
      {'title': '第三节：5-handlebar 辅助方法','duration':'1'},
      {'title': '第四节：5-handlebar 内建辅助方法','duration':'6'},
      {'title': '第一节：6-handlebar 基础','duration':'5'},
      {'title': '第二节：6-handlebar 表达式','duration':'3'},
      {'title': '第三节：6-handlebar 辅助方法','duration':'1'},
      {'title': '第四节：6-handlebar 内建辅助方法','duration':'6'}
  ]
};